# -*- coding: utf-8 -*-
"""instagram-fake-accounts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ySQQYj2oeG9chnw7z5ioRMJx9-rHmHd
"""

# A solução proposta para o problema do desconhecimento das contas fakes no Instagram (melhor descrito no relatório)
# consiste na criação de um modelo de classificação que define se uma conta é fake ou não de acordo com onze
# atributos da conta, como número de seguidores e seguindo, conta privada ou pública, número de posts, se a conta
# possui foto de perfil ou não, dentre outros.
# Desta forma, será possível determinar se contas no Instagram são fakes ou não e solucionando o problema apresentado
# no relatório.

# O dataset utilizado pode ser acessado no link abaixo.
# https://www.kaggle.com/free4ever1/instagram-fake-spammer-genuine-accounts

# Carregando e unindo os arquivos do dataset
import pandas as pd
arquivo1 = pd.read_csv('test.csv')
arquivo2 = pd.read_csv('train.csv')

# A união foi necessária para um split em que o 20% dos dados fossem para o teste e 80% para o treino
dados = pd.concat([arquivo1, arquivo2], axis=0)

# Visualização dos dados concatenados
dados

# Separando as variáveis entre preditoras e variável alvo
alvo = dados['fake']
pred = dados.drop('fake', axis = 1)

# Criando os conjuntos de dados de treino e teste
from sklearn.model_selection import train_test_split

pred_treino, pred_teste, alvo_treino, alvo_teste = train_test_split(pred, alvo, test_size = 0.2)

# Criação do modelo
from sklearn.ensemble import ExtraTreesClassifier

modelo = ExtraTreesClassifier()
modelo.fit(pred_treino, alvo_treino)

# Imprimindo os resultados
resultado = modelo.score(pred_teste, alvo_teste)
print('Acurácia:', resultado)

# Analisando a performance do algoritmo com uma amostra de três registros dos resultados dos testes
alvo_teste[20:23]

pred_teste[20:23]

previsoes_amostras = modelo.predict(pred_teste[20:23])

previsoes_amostras

# Conclusão

# Em minha percepção, a aplicabilidade da solução é alta, visto que o modelo possui mais de 90%
# de acurácia desenvolvido com um dataset com 696 registros. Acredito que, neste caso, a adição de mais
# exemplos no treinamento e teste do modelo corroboraria com uma melhor acurácia, e consequentemente,
# com a maior visibilidade das contas fakes do Instagram, ajudando de maneira eficaz no problema descrito no relatório.